### ISSUE TITLE
Tampermonkey Script

### ISSUE THREAD

**Issue by AyahRamahi** [kerolloz/follows-you-github#6]

**Comment by kerolloz** [comment]
Hello @AyahRamahi  😃 

Wow! Actually, this is very first time I hear about Tampermonkey. It sounds like a great extension. I liked the idea. Let me know how we can make use of it in _Follows You_. 

Yes, absolutely you can contribute. 💯

**Comment by AyahRamahi** [comment]
We can provide a script besides the extension to allow users to use it to add functionality. I'll check out the repo and start working on it. Will keep you updated!

Thanks.
