### ISSUE TITLE
[feature] add follow you in starred list

### ISSUE THREAD

**Issue by AhmedElTabarani** [kerolloz/follows-you-github#9]
Can add it to the starred list ?

## Repo's starred list
![image](https://user-images.githubusercontent.com/69223584/148244295-944de8b8-c6bc-4895-95f0-19d2f4c7e776.png)

## Gist' starred list
![image](https://user-images.githubusercontent.com/69223584/148244519-1146c4f5-29b3-46a7-ba54-ef02c32bf5af.png)

**Comment by kerolloz** [comment]
@AhmedElTabarani This is a great idea. But, unfortunately we have some limitations. For example, the GitHub API enforces a [rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)(60 requests per hour) on the API request that tells you whether a user is a follower. So, opening a list of stargazers would end up hitting this rate limit in a matter of seconds. 
However we still have a solution which is using a token to get a rather bigger number of requests, but that will lead to more complexity (i.e. asking the user to generate a token & implementing a user interface so the user can add the generated token to be used by the extension)

Luckily,  you can still see who follows you by hovering over their name in the stargazers list: 
![image](https://user-images.githubusercontent.com/36763164/148253692-24e9a851-53de-4b7a-b375-b3c3fb80dbaf.png)

This doesn't work on Gist yet. But, I'm on it. 🚧
